import Image from "next/image";
import "./styles/globals.css";
import Navbar from "@/app/_components/Navbar";
import Guide from "@/app/_components/Guide";
import Login from "@/app/_components/Login";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Noto+Sans+SC:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`antialiased`}>
        <main className="flex flex-col h-screen ">
          <div className="absolute inset-0 -z-10 w-full h-screen bg-[url('/river.jpg')] bg-cover bg-top bg-no-repeat opacity-25"></div>

          <Navbar />

          <div className="flex-1 flex">
            <Guide />
            <Login />
          </div>
        </main>

        {/* {children} */}
      </body>
    </html>
  );
}
