import Image from "next/image";
import "./styles/globals.css";
import Navbar from "@/app/_components/Navbar";
import Guide from "@/app/_components/Guide";
import Login from "@/app/_components/Login";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main className="flex flex-col h-screen ">
          <div className="absolute inset-0 -z-10 w-full h-screen bg-[url('/river.jpg')] bg-cover bg-top bg-no-repeat opacity-25"></div>

          <Navbar />

          <div className="flex-1 flex">
            <Guide />
            <Login />
          </div>
        </main>

        {/* {children} */}
      </body>
    </html>
  );
}
