name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'qujsh' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install and build
        run: |
          rm -rf dist/
          npm install
          npm run build
        shell: bash

      - name: Publish releases
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            npm exec electron-builder -- --mac --publish always
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            npm exec electron-builder -- --win --x64 --publish always
          fi
        shell: bash
